# Generated by Django 3.2 on 2021-04-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendor.customuser')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
            ],
        ),
    ]
